### ISSUE TITLE
Not all items in the recyclerview is being added to the pdf

### ISSUE THREAD

**Issue by GeorgeSanu05** [Gkemon/Android-XML-to-PDF-Generator#10]
To print a stock list used a scroll view containing recycler view inside it, and for a short amount of data's inside recycler view its working fine but when the amount of item's increase the pdf is only showing the data's at top of the recycler view and not the complete list.
Is there any solution to solve the issue...

**Comment by Gkemon** [comment]
@GeorgeSanu05  I already solved it yesterday night. And I will try to push it by today. I will email you when it will be available. Please then update the library version and let me know that is it ok or not. I will help you to resolve your issue. No problem.

**Comment by GeorgeSanu05** [comment]
@Gkemon  thank you for the reply. I will wait for your response

**Comment by Gkemon** [comment]
Hi Sanu, Good day.  please check my new release named  v.2.0 and let me
know that is it working or not. Thank you.

**Comment by GeorgeSanu05** [comment]
@Gkemon  thank you so much for helping,
I checked the latest version 2.0 it prints all the items in the recycler view but the only problem I felt in this version in relation to the earlier one is the file is not visible in the provided directory or folder.

**Comment by Gkemon** [comment]
yeah sanu, I'm trying to fix it. But now you can get the file path in the
success response. So primarily deal with this file path now. If I can fix
it then again knock you.

**Comment by Gkemon** [comment]
And If you find it helpful then you are most welcome to hit a star and
fork. Thank you.

**Comment by hemant00007** [comment]
I am showing data into the views, Recyclerview , but when i create pdf it show only initial views, not loading the json data into the pdf. Can you help me or please provide me a working example of how to create a pdf of network data. Thanks

**Comment by Gkemon** [comment]
@hemant00007  First of all, Thanks for your feedback. Can you please confirm that you are using the latest version of this library? It was the bug I already fixed a few days ago. If you are using the latest version then please share your code snippet also (XML and your java code). I will try to fix it if the issue exists yet.

**Comment by hemant00007** [comment]
implementation 'com.github.Gkemon:XML-to-PDF-generator:2.3'

**Comment by Gkemon** [comment]
@hemant00007  I got your problem bro. In the current implementation of this library, it is possible only to print the items which are showing in recycler view actually. And suppose you wanna print a recycler view that containing 100 items then you need to first load it into the recycler view then print it. 
If you think that showing 100 items for the user is a bad user experience then you can do a thing. Create the recycler view with 100 items but don't show it to users. Then just print it when users wants. [This ](https://github.com/Gkemon/Android-XML-to-PDF-Generator#from-views) part of the doc will help you very much. Just add your recycler view in a separate layout. Inflate the layout into a view object and finally print it.

**Comment by Gkemon** [comment]
Hi @hemant00007 @GeorgeSanu05 
Thank you all for the support. Please kindly star and fork and send me the app links you all are using it. If there is no confidentiality then I will list them in my **readme.md** file.
