### ISSUE TITLE
Folder is not created.file.mkdirs() is returning false - Android 10 and 11

### ISSUE THREAD

**Issue by lucasfelipes2395** [Gkemon/Android-XML-to-PDF-Generator#11]
I'm using your Android-XML-to-PDF-Generator api, but on android 10 and 11 the pdf is not displayed and this message appears in the log:

Folder is not created.file.mkdirs() is returning false
PDF file is not existing in storage. Your Generated path is /storage/emulated/0/teste/

I already put all the permissions:

```
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
```

what would be the solution?

**Comment by GeorgeSanu05** [comment]
@lucasfelipes2395 
### **android:requestLegacyExternalStorage="true"** 
try after giving this tag in your AndroidManifest.xml inside applicationTag

**Comment by Gkemon** [comment]
Hi Lucas, please check my new release named  v.2.0 and let me know that is
it working or not. Thank you.

**Comment by Gkemon** [comment]
Hi @lucasfelipes2395  @GeorgeSanu05 
Thank you all for the support. Please kindly star and fork and send me the app links you all are using it. If there is no confidentiality then I will list them in my **readme.md** file.
