### ISSUE TITLE
Size issue when adding array with views

### ISSUE THREAD

**Issue by veramdclu** [Gkemon/Android-XML-to-PDF-Generator#17]
when I add 5 views with .fromViewSource().fromView(v1, v2, v3, v4, v5) the width becomes smaller for each view. I have also tried to add the same view several times just to test and the result is the same, see attached picture. 
<img width="197" alt="Screendump 2021-04-05 kl  10 11 04" src="https://user-images.githubusercontent.com/69011058/113553883-b9689900-95f8-11eb-8e49-7ac254eee6e0.png">

**Comment by Gkemon** [comment]
Hi @veramdclu, Thanks for using this library and gave back your feedback. Please update your current library version into **2.4** in which I actually fixed your observed bug.

**Comment by jc-yoonet** [comment]
Still happens in 2.5

I'm using this in my view.

`<?xml version="1.0" encoding="utf-8"?>
<ImageView 
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/image"
    tools:src="@mipmap/ic_launcher"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:scaleType="centerInside" />`

![wJs6opAv9O](https://user-images.githubusercontent.com/69573046/144361548-ff71945b-bc6a-4b85-8b12-ea9349718fdb.gif)


Thanks for this library, nice and fast.
