### ISSUE TITLE
Layout data not showing

### ISSUE THREAD

**Issue by amila4d** [Gkemon/Android-XML-to-PDF-Generator#18]
XML layout data not showing in pdf file. Eg: If we have recycler view inside xml layout, that data does not shows in pdf. Same as edit text data inside xml. Any luck?

**Comment by Gkemon** [comment]
Hi @amila4d  .First Thanks for using my library. If you face any trouble to print docs then you can see my example of [How to print an Invoice or Report?](https://github.com/Gkemon/Android-XML-to-PDF-Generator/blob/master/README.md#how-to-print-an-invoice-or-report-). Comment here if you have any query.

**Comment by Gkemon** [comment]
Hi @amila4d , If you are still facing any problem then reopen it or knock me before following my latest comment.
