### ISSUE TITLE
Nothing is happening

### ISSUE THREAD

**Issue by pierrekhouryy** [Gkemon/Android-XML-to-PDF-Generator#2]
when I run the following from Project A it ran perfectly, but when I copy pasted it into Project B nothing happens, even the showLog method is not called.

>    Context context = requireContext();
        View voew = LayoutInflater.from(context).inflate(R.layout.layout_invoiceitem,null);
        PdfGenerator.getBuilder()
                .setContext(context)
                .fromViewSource()
                .fromView(voew)
                .setCustomPageSize(500,1000)
                .setFileName("testbeta4")
                .setFolderName("FolderB")
                .openPDFafterGeneration(true)
                .build(new PdfGeneratorListener() {
                    @Override
                    public void onFailure(FailureResponse failureResponse) {
                        super.onFailure(failureResponse);
                    }
                    @Override
                    public void showLog(String log) {
                        super.showLog(log);
                    }
                    @Override
                    public void onSuccess(SuccessResponse response) {
                        super.onSuccess(response);
                    }
                });

**Comment by Gkemon** [comment]
Do you attached debugger in `onSuccess(SuccessResponse response)` and `onFailure(FailureResponse failureResponse) ` also? please check it. And make sure that you give the all neccessary permissions.

**Comment by pierrekhouryy** [comment]
@Gkemon You are correctI was not giving the necessary permissions.  I was not putting <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/> in the android manifest. Thanks!

**Comment by Gkemon** [comment]
You are welcomed and also thank you for testing.

**Comment by Gkemon** [comment]
Hi @pierrekhouryy  
Thank you all for the support. Please kindly star and fork and send me the app links you all are using it. If there is no confidentiality then I will list them in my readme.md file.
