### ISSUE TITLE
Remove setting width and height of PDF

### ISSUE THREAD

**Issue by Gkemon** [Gkemon/Android-XML-to-PDF-Generator#25]
For printing well-formed ISO standard-sized papers(like A4,A5 sized pdf, you don't need to be concerned about width and height. Please set width and height to the XML with an aspect ratio of 1:√2. For example, if your xml width is 100 dp then the height of the xml will be (100 X √2) = 142 dp. Finally when we print them with any kind of ISO standard paper, then they will be auto-scaled and fit into the specific paper.
Reference:http://tolerancing.net/engineering-drawing/paper-size.html

**Comment by TanvirTaaha** [comment]
Even after setting width height with specific dp value as suggested, the generated pdf becomes much wider
the pdf was generated from View-Source not the xml.
how to fix this? tried setting height width programmatically as well
[xml file](https://github.com/Gkemon/Android-XML-to-PDF-Generator/files/6650482/activity_prescription_details_2.txt)

**Comment by Gkemon** [comment]
Hi Mr @TanvirTaaha , Good evening. Thanks for using my library. Can you please ensure me which version of library are you using?

**Comment by TanvirTaaha** [comment]
Version 2.5

**Comment by Gkemon** [comment]
Hi @TanvirTaaha  vaiya. Sorry for late reply. Please try to set the width as a fixed width instead of match parent and fix the design according to this. Then I thing it will work as expected.You can also have a look on my demonstration [here](https://github.com/Gkemon/Android-XML-to-PDF-Generator/tree/master/sample/src/main/java/com/emon/exampleXMLtoPDF/demoInvoice). Please knock me if face any trouble. Thank you.

**Comment by Gkemon** [comment]
Hi @TanvirTaaha 
Thank you all for the support. Please kindly star and fork and send me the app links you all are using it. If there is no confidentiality then I will list them in my **readme.md** file.
