### ISSUE TITLE
Recyclerview in running activity showdata but in pdf not showing data

### ISSUE THREAD

**Issue by akumakhalibagas** [Gkemon/Android-XML-to-PDF-Generator#27]

**Comment by Gkemon** [comment]
Hi @akumakhalibagas  sorry for the late reply , Please check my demonstration [here](https://github.com/Gkemon/Android-XML-to-PDF-Generator/tree/master/sample/src/main/java/com/emon/exampleXMLtoPDF/demoInvoice). If you face stuck then knock me by comment here and if possible then please post here your code also. I think you are putting the only xml into the pdf generator not the view instance. If anyone wants to set dynamic view in pdf generation then he had to put the view instance into it. Thank you

**Comment by Gkemon** [comment]
Hi @akumakhalibagas 
Thank you all for the support. Please kindly star and fork and send me the app links you all are using it. If there is no confidentiality then I will list them in my **readme.md** file.
