### ISSUE TITLE
Data Not Showing

### ISSUE THREAD

**Issue by AzharRivaldi** [Gkemon/Android-XML-to-PDF-Generator#28]
Hello. i fetch data from API by retrofit and i put it in textview, but when creating pdf the data doesn't show.  pdf is just blank.  what's the solution?

**Comment by Gkemon** [comment]
Hi @AzharRivaldi  sorry for the late reply. Please see my [this](https://github.com/Gkemon/Android-XML-to-PDF-Generator/tree/master/sample/src/main/java/com/emon/exampleXMLtoPDF/demoInvoice)  demonstration where I showed how to generate data before print. Make sure that you are prepopulating all necessary views before pushing it into the Pdf generator. Knock me if faced trouble. Thank you.

**Comment by Gkemon** [comment]
Hi @AzharRivaldi 
Thank you all for the support. Please kindly star and fork and send me the app links you all are using it. If there is no confidentiality then I will list them in my **readme.md** file.
