### ISSUE TITLE
 No such file or directory in android 10

### ISSUE THREAD

**Issue by dondeepak** [Gkemon/Android-XML-to-PDF-Generator#3]
its working on android 9 but in android 10 i get error
/storage/emulated/0/Test-PDF-folder/TestPDF.pdf: open failed: ENOENT (No such file or directory)

**Comment by gaurav844** [comment]
same issue please fix

**Comment by gaurav844** [comment]
Found solution  ! check this out
https://stackoverflow.com/questions/61629593/no-such-file-or-directory-in-android-10-api-29

**Comment by Gkemon** [comment]
@gaurav844  Thank you, Gaurav.For your nice solution. Summary is just that just add -
 `android:requestLegacyExternalStorage="true"  ` 
in between `<application>...</application>` in Menifest.

**Comment by Gkemon** [comment]
Hi @dondeepak @gaurav844  
Thank you all for the support. Please kindly star and fork and send me the app links you all are using it. If there is no confidentiality then I will list them in my **readme.md** file.
