### ISSUE TITLE
Change the Directory Path

### ISSUE THREAD

**Issue by UsamaAliBhatti** [Gkemon/Android-XML-to-PDF-Generator#30]
I want to change the path of the saving pdf after converting to pdf. Please help/guide to get that stuff done

**Comment by Gkemon** [comment]
Hi @UsamaAliBhatti  bhaiya, sorry for the late reply. Here is the [documentation](https://github.com/Gkemon/Android-XML-to-PDF-Generator#from-layout-resources-). Please set path via this function -  
`.setFolderName("FolderA/FolderB/FolderC")`
Please knock me if also find any trouble after that. Thank you.
