### ISSUE TITLE
Pdf not generating

### ISSUE THREAD

**Issue by munishkumarwinapp** [Gkemon/Android-XML-to-PDF-Generator#31]
i got this error

 Page Width must be positive

**Comment by munishkumarwinapp** [comment]
Please help me  this is my code
  PdfGenerator.getBuilder()
            .setContext(this@OrderDetailScreenActivity)
            .fromViewSource()
            .fromView(content)
            .setFileName("Test-PDF")
            .setFolderName("Test-PDF-folder")
            .openPDFafterGeneration(true)
            .build(object : PdfGeneratorListener() {
                override fun onFailure(failureResponse: FailureResponse) {
                                        Log.e("Failure Response", failureResponse.errorMessage)
                    Toast.makeText(
                        this@OrderDetailScreenActivity,
                        "" + failureResponse.getErrorMessage(),
                        Toast.LENGTH_SHORT
                    ).show();
                    super.onFailure(failureResponse)
                }

                override fun showLog(log: String) {
                    super.showLog(log)
                }

                override fun onStartPDFGeneration() {
                    /*When PDF generation begins to start*/
                }

                override fun onFinishPDFGeneration() {
                    Log.e("Successs", "Pdg Generation success")
                    /*When PDF generation is finished*/
                }

                override fun onSuccess(response: SuccessResponse) {
                    super.onSuccess(response)
                }
            })

**Comment by Gkemon** [comment]
Hi @munishkumarwinapp sorry for the late reply. Please check the latest version and if get stuck then please knock me here or via email with your XML code snipet. Thank you

**Comment by Gkemon** [comment]
Hi @munishkumarwinapp 
Thank you all for the support. Please kindly star and fork and send me the app links you all are using it. If there is no confidentiality then I will list them in my **readme.md** file.
