### ISSUE TITLE
How can i set default size of generated layout?

### ISSUE THREAD

**Issue by surajsahani** [Gkemon/Android-XML-to-PDF-Generator#32]
.setDefaultPageSize(PdfGenerator.PageSize.A4)

tried this but now working

**Comment by Gkemon** [comment]
Hi @surajsahani  , Sorry for the late reply.  As setting size created trouble in some use cases so I remove these functions in new version and now it is getting height width from layout XML here it is defined..Please use the latest library. I'm also trying to push a new release in-between the next few days.   Knock me here if need help further and thank you for your feedback.

**Comment by Gkemon** [comment]
Hi @surajsahani 
Thank you all for the support. Please kindly star and fork and send me the app links you all are using it. If there is no confidentiality then I will list them in my **readme.md** file.
