### ISSUE TITLE
Recycler view

### ISSUE THREAD

**Issue by sanjaymeena93** [Gkemon/Android-XML-to-PDF-Generator#33]
How to create single pdf file with multiple pages using recycler view and one thing this recycler view item should be customize

**Comment by Gkemon** [comment]
Hi @sanjaymeena93  [Here](https://github.com/Gkemon/Android-XML-to-PDF-Generator/tree/master/sample/src/main/java/com/emon/exampleXMLtoPDF) is a sample project where I showed how to generate a pdf containing a list or recycler view. If faced any trouble then comment here or email me. I will try to help as much as possible.

**Comment by Gkemon** [comment]
Hi @sanjaymeena93 
Thank you all for the support. Please kindly star and fork and send me the app links you all are using it. If there is no confidentiality then I will list them in my **readme.md** file.
