### ISSUE TITLE
only single page pdf 

### ISSUE THREAD

**Issue by sanjaymeena93** [Gkemon/Android-XML-to-PDF-Generator#34]
only single page pdf is generated. how to generate multiple pages of pdf

**Comment by Gkemon** [comment]
Hi @sanjaymeena93 ,sorry for the late reply. Here is my [doc](https://github.com/Gkemon/Android-XML-to-PDF-Generator#multi-paged-pdf-creation) where I showed how to generate multiple pages in a pdf file. If facing trouble and need any help then please knock me here or my email address. Thank you. I will reopen the issue if necessary.

**Comment by Gkemon** [comment]
Hi @sanjaymeena93  
Thank you all for the support. Please kindly star and fork and send me the app links you all are using it. If there is no confidentiality then I will list them in my **readme.md** file.
