### ISSUE TITLE
Size issue

### ISSUE THREAD

**Issue by pavan2991sharma** [Gkemon/Android-XML-to-PDF-Generator#36]
Pdf is generating but during print from desktop pdf is not printing in A4 size.it prints in the middle of page like a vertical row.

**Comment by Gkemon** [comment]
Hi @pavan2991sharma, sorry for the late reply. A4 page size aspected ratio is 1:1.4142. So please try to set width height to your XML respecting this ratio and design all of your components in it. Then hopefully it will work as expected. If you face any stuck then please knock me here. I will try to help you and reopen this issue if necessary.

**Comment by Gkemon** [comment]
You can also run my sample app to see my[ demo invoice](https://github.com/Gkemon/Android-XML-to-PDF-Generator/tree/master/sample/src/main/java/com/emon/exampleXMLtoPDF/demoInvoice) printing demonstration

**Comment by Gkemon** [comment]
Hi @pavan2991sharma  
Thank you all for the support. Please kindly star and fork and send me the app links you all are using it. If there is no confidentiality then I will list them in my **readme.md** file.
