### ISSUE TITLE
Listview within a fragment ?

### ISSUE THREAD

**Issue by 1stmetro** [Gkemon/Android-XML-to-PDF-Generator#37]
Hi, I am trying to get this to work with a listview within a fragment, I cant seem to get the ids to work if I use the view it will also not work and how do i size things within the final pdf as everything always appears giant.

Thanks to anyone for replying.

**Comment by Gkemon** [comment]
@1stmetro  Sorry for the late reply. Can you please share your XML and java code and the output PDF? Here is my [sample](https://github.com/Gkemon/Android-XML-to-PDF-Generator/tree/master/sample/src/main/java/com/emon/exampleXMLtoPDF/dummyList) of how to deal with list view. You can run my "sample" project and test the list view printing by uncommenting the related code.  I will reopen the issue if you can't deal with it. Comment here by mentioning me if get stuck. Thank you

**Comment by Gkemon** [comment]
Hi @1stmetro 
Thank you all for the support. Please kindly star and fork and send me the app links you all are using it. If there is no confidentiality then I will list them in my **readme.md** file.
