### ISSUE TITLE
WRITE_EXTERNAL_STORAGE permission not granted even after permission has been granted.

### ISSUE THREAD

**Issue by shafayatb** [Gkemon/Android-XML-to-PDF-Generator#38]
Hello,
I was getting WRITE_EXTERNAL_STORAGE even after approving the permissions in the app. For now I fixed by adding the write permission in the manifest file like this,

`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"  tools:node="replace" />`

**Comment by Gkemon** [comment]
Hi @shafayatb  bhaiya, sorry for the late reply. I tried to generate it but can't. I even did a commit by removing my app-level storage permission and it is working for me as previously. It will be helpful to me if you guide me to generate it with a proper explanation. I will reopen the issue again if necessary. Thank you.

**Comment by Gkemon** [comment]
Hi @shafayatb 
Thank you all for the support. Please kindly star and fork and send me the app links you all are using it. If there is no confidentiality then I will list them in my **readme.md** file.
