### ISSUE TITLE
Not working after updating view problematically

### ISSUE THREAD

**Issue by gaurav844** [Gkemon/Android-XML-to-PDF-Generator#4]
only static view is printing

**Comment by Gkemon** [comment]
Actually, I tried to regenerate your issue but can't but I can recommend you my way to update the view programmatically before print. 

**Step 1:** First create an inflated view object from your XML. For example - 
` View content = inflater.inflate(R.layout.layout_myl, null);`

**Step 2:** Suppose, you wanna update a `TextView` inside the `content` object _( That means a TextView inside `layout_my.xml`)_ 
then you make an instance of that object and update the content of that `TextView`. For example - 
              TextView textView = content.findViewById(R.id.tv_text);
              textView.setText("Updated content");

**Step 3:** Finally follow my step, [how to print pdf from java view instance ](https://github.com/Gkemon/Android-XML-to-PDF-Generator#from-views). My full example is -

```
                View content = inflater.inflate(R.layout.layout_print, null);
                TextView textView = content.findViewById(R.id.tv_text);
                textView.setText("Updated content");

                  PdfGenerator.getBuilder()
                        .setContext(MainActivity.this)
                        .fromViewSource()
                        .fromView(content)
                        .setDefaultPageSize(PdfGenerator.PageSize.A4)
                        .setFileName("TestPDF")
                        .setFolderName("Test-PDF-folder")
                        .openPDFafterGeneration(true)
                        .build() 
```


If you found any problem with this approach then knock me. Thank you.

**Comment by maxx2478** [comment]
@Gkemon Thanks for the solution but when I'd updated an Imageview using the same way as you wrote about for other views, It didn't reflected in generated pdf. Here is my code:

```
View content = getLayoutInflater().inflate(R.layout.id_card_print, null);
 TextView textView = content.findViewById(R.id.name);
 TextView textView2 = content.findViewById(R.id.designation);
 TextView textView3 = content.findViewById(R.id.phonenumber);
 ImageView profile = content.findViewById(R.id.profile);


if (sessionManager.getUserDetails()!=null)
{
textView.setText("Name: "+sessionManager.getUserDetails().getName());
textView2.setText(Designation: "+sessionManager.getUserDetails().getDesignation());
textView3.setText("Mobile Number: "+sessionManager.getUserDetails().getMobile_number());
				
//Updating profile (imageview)
Glide.with(context).load(sessionManager.getUserDetails().getProfileImage()).
	placeholder(context.getResources().getDrawable(R.drawable.ic_user)).
	error(context.getResources().getDrawable(R.drawable.ic_user)).into(profile);

}
```
How can I resolve this?
Thanks for the awesome library !

**Comment by Gkemon** [comment]
Hi @maxx2478,You are welcome.  If you face any trouble to print docs then you can see my example of [How to print an Invoice or Report?](https://github.com/Gkemon/Android-XML-to-PDF-Generator/blob/master/README.md#how-to-print-an-invoice-or-report-)
