### ISSUE TITLE
Share generated pdf

### ISSUE THREAD

**Issue by hvcoder9** [Gkemon/Android-XML-to-PDF-Generator#40]
How can i share PDF generated by this library

**Comment by Gkemon** [comment]
For now please save the pdf in somewhere then share it. Hope I can introduce the feature in a short time.

**Comment by hvcoder9** [comment]
okay

**Comment by hvcoder9** [comment]
can u tell me how can i save generated pdf

**Comment by Gkemon** [comment]
Please check in the new version

**Comment by luistrejo033** [comment]
Hello @Gkemon !

Currently the library allows to share or open the pdf document created by default is in open, we could add a third option that is "nothing", to do nothing at the end of generating it, this would be useful when the same application manages the newly created file.

**Comment by Gkemon** [comment]
Hi @hvcoder9  and @hvcoder9  , I add this enhancement. Please check. 
Thank you all for the support. Please kindly star and fork and send me the app links you all are using it. If there is no confidentiality then I will list them in my readme.md file.
