### ISSUE TITLE
Skipping Horizontal Scrolled View

### ISSUE THREAD

**Issue by hanzlasheikh** [Gkemon/Android-XML-to-PDF-Generator#41]
I faced an issue when I was generating a pdf from a layout that contains a horizontally scrollable view. Some content was missed is there a way that it can show the content that was skipped horizontally

**Comment by GkEmonGON** [comment]
If no problem , can you share your XML and a screenshot how was the PDF you want to generate and your current output.

**Comment by Gkemon** [comment]
@hanzlasheikh  If no problem then can share the xml, I will try to regenerate it.

**Comment by GkEmonGON** [comment]
Hi @hanzlasheikh  , I can print a horizontal scroll view in my sample project - https://github.com/Gkemon/Android-XML-to-PDF-Generator/blob/master/sample/src/main/java/com/emon/exampleXMLtoPDF/MainActivity.java . 
And it is showing right. I might be wrong so please ping me again if it is not working. I will reopen it again. Thank you.
