### ISSUE TITLE
Pdf is saved under data folder

### ISSUE THREAD

**Issue by sparjapati** [Gkemon/Android-XML-to-PDF-Generator#42]
Pdf is always saved under **`Android/data/{packageName}`** directory even when I specified the location using
`.setFolderNameOrPath("${Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOCUMENTS).path}/${getString(R.string.app_name)}")`. Is there any method to change this?

**Comment by ZyanE123** [comment]
I couldn't stop it from being saved in data folder. I used a FileProvider to access the file and use it in external storage.

**Comment by Gkemon** [comment]
@sparjapati  and @sparjapati  Thanks for the reporting, I have already done it. I can check the commit. Will release it soon.

**Comment by Gkemon** [comment]
Please check in the new version

**Comment by Gkemon** [comment]
@sparjapati  , please try to set it like that - 
`.setFolderNameOrPath(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOCUMENTS).path+getString(R.string.app_name));`

**Comment by theMr17** [comment]
@Gkemon The pdf is not getting saved. When I try to search in the Files, I get no such PDF which got generated.

**Comment by Gkemon** [comment]
Hi @the-future-warrior  you can open the pdf after generation with this param.  `.actionAfterPDFGeneration(PdfGenerator.ActionAfterPDFGeneration.OPEN)`
Please see the doc and let me know if find anything problematic

**Comment by theMr17** [comment]
@Gkemon  Thanks for the quick response.
The issue is as follows
1. The PDF is opening properly with the above param, but when I try to find the pdf which got generated, I am **unable to find that anywhere** in the storage.
2. Secondly, `.actionAfterPDFGeneration(PdfGenerator.ActionAfterPDFGeneration.SHARE)` is not working. When I try to share via Whatsapp or Telegram, it says that **unsupported format**

**Comment by Gkemon** [comment]
Hi @the-future-warrior  , Thanks for the feedback. Ok, I'm reopening the issue again. If possible try to run it locally and figure out the issue then pull request me. It will be a great of all.

**Comment by theMr17** [comment]
@Gkemon It will be greatly appreciated, if you would solve this issue as soon as possible because I have implemented your library in my app, which I am planning to launch within few days....

**Comment by Gkemon** [comment]
Hi @the-future-warrior  Please check the new release **v2.6.4**

**Comment by umer7267** [comment]
I am unable to find the pdf file in the file manager while it exists in the Documents folder. How to get the pdf also show in the file manager? I think .handleInFileStorage(true,true) should work but it does not exist anymore.

**Comment by GkEmonGON** [comment]
hi @umer7267  bhai, Please make it sure that user is savings the PDF after opening and which is the last recommended approach to save a data in store.
