### ISSUE TITLE
Setting gravity of an edit text causes problem

### ISSUE THREAD

**Issue by ZyanE123** [Gkemon/Android-XML-to-PDF-Generator#43]
I am using this library to create a pdf with views that have been updated. I have not run into any problems and have it fully functioning. But I decided I wanted to center the text in an Edit Text and found that it would display as blank if the gravity was changed.

I have attached a screenshot from the pdf the edit texts labeled "flow rate" are updated just fine when the pdf was created.
The ones labeled "Current" have had their gravity set to center horizontal and do not print

![gravity-04 101252](https://user-images.githubusercontent.com/84121804/166700100-db596c93-3e93-452b-ab31-7628f638d617.png)

**Comment by Gkemon** [comment]
Can you share the XML of this @ZyanE123 ? And make sure that in the preview, you are showing the Flow Rate in the center.

**Comment by Gkemon** [comment]
Hi @ZyanE123  please when you will share the XML and if I found any issue it library then I will reopen the issue again. If it is for your code issue then I will also. Thank you.
