### ISSUE TITLE
Not working on Andoird11 or API 30

### ISSUE THREAD

**Issue by tanvirnexus** [Gkemon/Android-XML-to-PDF-Generator#44]
It's not working on Andoird11 or API 30. Please, take a look at the logs:

`Log: WRITE_EXTERNAL_STORAGE and READ_EXTERNAL_STORAGE Permission is not given. Permission taking popup (using https://github.com/Karumi/Dexter) is going to be shown
Log: Denied permission: android.permission.WRITE_EXTERNAL_STORAGE
Log: Granted permission: android.permission.READ_EXTERNAL_STORAGE
Log: All necessary permission is not granted by user.Please do that first`

You know Android 11 doesn't offer WRITE_EXTERNAL_STORAGE it offers MANAGE_EXTERNAL_STORAGE if your app primarily focuses on files management. They recommend using MediaStorage API instead. I submitted my app with MANAGE_EXTERNAL_STORAGE but they rejected it and told me to use MediaStorage. 

Please, consider the issue. My app is production-ready, but I'm stuck here.

**Comment by Gkemon** [comment]
Hi @tanvir93  bhaiya, sorry for the late reply. I run my sample app in android 11 but it is still working and not generating any error like that. can you check my sample app please - https://github.com/Gkemon/Android-XML-to-PDF-Generator/tree/master/sample ? It is configured also for android 11 well. I might be wrong. If you also found the sample is buggy then I will reopen the issue. Thank you.

**Comment by Gkemon** [comment]
Hi @tanvir93 
Thank you all for the support. Please kindly star and fork and send me the app links you all are using it. If there is no confidentiality then I will list them in my readme.md file.
