### ISSUE TITLE
how to adjust my layout to A4 Paper?

### ISSUE THREAD

**Issue by dor19741** [Gkemon/Android-XML-to-PDF-Generator#46]
PdfGenerator.a4WidthInPostScript

i saw this command but idk whrere i can use this command , which method i need to use / enable in order to acheive a pdf adpative it to A4

**Comment by fzanutto** [comment]
Would it be `PdfGenerator.getBuilder().setPageSize(PdfGenerator.PageSize.A4)` ?

**Comment by mujahid-dzinemedia** [comment]
PdfGenerator.getBuilder().setPageSize(PdfGenerator.PageSize.A4) not found in latest release

**Comment by Gkemon** [comment]
Hi, @fernandozanutto @dor19741  @mujahid-dzinemedia  sorry for the late reply. Please check my documents where I just mentioned it more clearly than previously.
https://github.com/Gkemon/Android-XML-to-PDF-Generator/blob/master/README.md#-important-note
 For some issues _(It causes the pdf sometimes to be malformed)_, I removed the page size insertion functions. Thank you.

**Comment by Gkemon** [comment]
Hi @fernandozanutto @dor19741 @mujahid-dzinemedia 
Thank you all for the support. Please kindly star and fork and send me the app links you all are using it. If there is no confidentiality then I will list them in my readme.md file.
