### ISSUE TITLE
dependency link wrong in documentation

### ISSUE THREAD

**Issue by Kayuemkhan** [Gkemon/Android-XML-to-PDF-Generator#48]
Please check this part in documentation. **The string is not **completed****.

Replace your line with this:

    implementation 'com.github.Gkemon:Android-XML-to-PDF-Generator:2.6.2'

![image](https://user-images.githubusercontent.com/28877375/189862149-02b528b0-990a-4813-b875-2450ca3d4468.png)

**Comment by Gkemon** [comment]
Hi @Kayuemkhan  bhai, fixed and thanks
