### ISSUE TITLE
How to add multiples pdf pages

### ISSUE THREAD

**Issue by mealiraza** [Gkemon/Android-XML-to-PDF-Generator#5]

**Comment by Gkemon** [comment]
You just put multiple layouts or view id or views in the method for example   `.fromLayoutXML(R.layout.layout_print, R.layout.layout_print) `then it will generate multiple pages for you.

**Comment by Gkemon** [comment]
Hi @MrAliRaxa , you can do that using the current version. Please see the [document]( https://github.com/Gkemon/Android-XML-to-PDF-Generator#from-layout-resources-).  
You can insert multiple xml or views object even view id in the parameter of the  following methods : 

If you want create multi-paged pdf from xml-
`.fromLayoutXML(R.layout.layout_print,R.layout.layout_print)`

 If you want create multi-paged pdf from view ids -
`.fromViewID(activity,R.id.viewId1,R.id.viewId2)`

 If you want create multi-paged pdf from views-
`.fromViewID(view1,view1)`

So if you find any trouble,then you are also welcomed again to knock me.

**Comment by mealiraza** [comment]
Thanks bro how i render a recyclerview in pdf

**Comment by Gkemon** [comment]
Did you mean,you are willing to print per item of the recyclerview in per
page of the pdf ??

**Comment by mealiraza** [comment]
May be one item or 6 or 10 items
