### ISSUE TITLE
page becomes mess

### ISSUE THREAD

**Issue by dondeepak** [Gkemon/Android-XML-to-PDF-Generator#6]
After creating pdf page view becomes complete mess

     PdfGenerator.getBuilder()
                .setContext(lActivity.this)
                .fromViewIDSource()
           
                .fromViewID(GattDetailActivity.this, R.id.scrollview)
                .setCustomPageSize(	720,1280)
               // .setDefaultPageSize(PdfGenerator.PageSize.A4)
                .setFileName("Report")
                .setFolderName("Report")
                .openPDFafterGeneration(true)
                .build(new PdfGeneratorListener() {
                    @Override
                    public void onFailure(FailureResponse failureResponse) {
                        Toast.makeText(Activity.this, "Error！" + failureResponse.getErrorMessage().toString(), Toast.LENGTH_SHORT).show();
                        super.onFailure(failureResponse);

                    }

                    @Override
                    public void showLog(String log) {
                        super.showLog(log);
                    }

                    @Override
                    public void onSuccess(SuccessResponse response) {
                        super.onSuccess(response);
                        // Toast.makeText(Activity.this, response.toString(), Toast.LENGTH_SHORT).show();
                    }
                });
please help
![Screenshot_20201122-221155_USRBleAssistent](https://user-images.githubusercontent.com/24863950/99909704-0602a600-2ce2-11eb-9e4a-008e82f1d00b.jpg)
![Screenshot_20201122-221205_USRBleAssistent](https://user-images.githubusercontent.com/24863950/99909708-0a2ec380-2ce2-11eb-9523-765eed693d8d.jpg)

**Comment by Gkemon** [comment]
Dose it in scrolling layout?

**Comment by Gkemon** [comment]
Hi Sanu, deepak , Good day.  please check my new release named  v.2.0 and let me know that is it working or not. Thank you. If it doesn't work then knock me again kindly.

**Comment by Gkemon** [comment]
Hi @dondeepak  
Thank you all for the support. Please kindly star and fork and send me the app links you all are using it. If there is no confidentiality then I will list them in my **readme.md** file.
