### ISSUE TITLE
NOT WORKING  IN ANDROID 13

### ISSUE THREAD

**Issue by shubhamshreesri** [Gkemon/Android-XML-to-PDF-Generator#60]
THIS LIBRARY NOT WORKING IN ANDROID 13 BECAUSE OF PERMISSIONS ISSUES!

**Comment by Gkemon** [comment]
Please take a look at this implementation which is supported for Android 13. 
https://github.com/Gkemon/Android-XML-to-PDF-Generator/blob/master/sample/src/main/java/com/emon/exampleXMLtoPDF/MainActivity.java
If you find any problem with it, then kindly comment here.
