### ISSUE TITLE
What if I want to save pdf in internal storage either as persistent file or cache file?

### ISSUE THREAD

**Issue by momersaleem** [Gkemon/Android-XML-to-PDF-Generator#7]
Hello,

I want to save pdf file in internal storage instead of saving in external storage which requires to allow storage permissions. Please guide.

**Comment by Gkemon** [comment]
First of all, you need to give all the necessary permissions for storage read-write. Make sure that your manifest has permission. Then you have to take the user's run time permission. For taking runtime permission, I always use this library which reduces a ton of code for taking run time permission. https://github.com/Karumi/Dexter. 

Then  just put your desired path (whatever it is internal or external) in `.setFolderName()`, for example - `.setFolderName(/storage/sdcard1/myfolder)`. 

If you want to find your internal storage path then go to this -> https://stackoverflow.com/questions/37497566/android-find-path-android-in-internal-storage
