### ISSUE TITLE
multipage issue

### ISSUE THREAD

**Issue by taseercahmed** [Gkemon/Android-XML-to-PDF-Generator#9]
cannot go to multipage . please give this option

**Comment by Gkemon** [comment]
Hi @taseercahmed , you can do that using the current version. Please see the [document]( https://github.com/Gkemon/Android-XML-to-PDF-Generator#from-layout-resources-).  
You can insert multiple xml or views object even view id in the parameter of the  following methods : 

If you want create multi-paged pdf from xml-
`.fromLayoutXML(R.layout.layout_print,R.layout.layout_print)`

 If you want create multi-paged pdf from view ids -
`.fromViewID(activity,R.id.viewId1,R.id.viewId2)`

 If you want create multi-paged pdf from views-
`.fromViewID(view1,view1)`

So if you find any trouble,then you are also welcomed again to knock me.

**Comment by Gkemon** [comment]
Hi @taseercahmed 
Thank you all for the support. Please kindly star and fork and send me the app links you all are using it. If there is no confidentiality then I will list them in my **readme.md** file.
